"""Generated by scripts/sync_release_manifest.py; do not edit."""

PRODUCT = 'O.R.I.O.N.'
PRODUCT_NAME = 'Operational Response and Intelligent Orchestration Network'
INTERFACE_NAME = 'Aurora OS'
VERSION = '6.7.0'
VERSION_LABEL = "v" + VERSION
RELEASE_CHANNEL = 'development'
RELEASE_NAME = 'Aurora Mission Control'
