import { create } from "zustand";
import type { AuroraDashboardViewId, AuroraPanelId, AuroraPanelLayoutItem } from "@/types/panels";
import { loadActiveDashboardView, loadPanelLayoutFromStorage, resetPanelLayoutStorage, saveActiveDashboardView, savePanelLayoutToStorage } from "@/lib/panelLayoutStorage";
import { createLayoutFromPreset, sortPanelLayout } from "@/lib/panelRegistry";

import type {
  BackendSidecarStatus, DashboardIntelligence, DesktopShellStatus,
  FrontendRefactorResult, NotificationEventItem, PluginItem,
  ReleaseCandidatePackage, ReleaseCandidateStatus, ReminderItem,
  SecurityPolicyEventItem, SecurityProfileItem, StabilizationResult,
  StartupBriefing, ToolAuditEventItem, ToolPermissionItem, UserSettingsProfile,
} from "@/types/orion";
import { getDashboardIntelligence } from "@/lib/api/dashboard";
import { getDesktopShellStatus } from "@/lib/api/desktop";
import { getFrontendRefactorStatus, saveFrontendRefactorReport } from "@/lib/api/frontend-refactor";
import { createReminder, getNotificationEvents, getReminders, getStartupBriefing, updateReminderStatus } from "@/lib/api/notifications";
import { getPlugins, updatePluginStatus } from "@/lib/api/plugins";
import { freezeReleaseCandidate, generateReleaseCandidatePackage, getReleaseCandidateStatus, unfreezeReleaseCandidate } from "@/lib/api/release";
import { applySecurityProfile, getSecurityPolicy } from "@/lib/api/security";
import { getUserSettingsProfile, resetUserSettings, updateUserSetting } from "@/lib/api/settings";
import { getBackendSidecarStatus, runBackendSidecarAction } from "@/lib/api/sidecar";
import { runStabilizationScan, saveStabilizationReport } from "@/lib/api/stabilization";
import { getToolAudit, getToolPermissions } from "@/lib/api/tools";

type SidecarAction = "start" | "stop" | "restart";
type Store = {
  dashboardIntelligence: DashboardIntelligence | null; dashboardIntelligenceLoading: boolean;
  plugins: PluginItem[]; pluginMetrics: Record<string, unknown>; pluginRegistryReport: string; pluginLoadingKey: string | null;
  toolPermissionMatrix: ToolPermissionItem[]; toolPermissionMetrics: Record<string, unknown>; toolPermissionReport: string;
  toolAuditEvents: ToolAuditEventItem[]; toolAuditMetrics: Record<string, unknown>; toolAuditReport: string;
  securityProfiles: SecurityProfileItem[]; securityPolicyEvents: SecurityPolicyEventItem[]; securityPolicyActive: Record<string, unknown>; securityPolicyReport: string; securityPolicyLoadingKey: string | null;
  releaseCandidateStatus: ReleaseCandidateStatus | null; releaseCandidatePackage: ReleaseCandidatePackage | null; releaseCandidateLoading: boolean;
  stabilizationResult: StabilizationResult | null; stabilizationLoading: boolean;
  frontendRefactorResult: FrontendRefactorResult | null; frontendRefactorLoading: boolean;
  desktopShellStatus: DesktopShellStatus | null; desktopShellLoading: boolean;
  backendSidecarStatus: BackendSidecarStatus | null; backendSidecarLoading: boolean;
  reminders: ReminderItem[]; notificationEvents: NotificationEventItem[]; startupBriefing: StartupBriefing | null; reminderTitle: string; reminderDueAt: string; reminderLoading: boolean;
  userSettingsProfile: UserSettingsProfile | null; settingsLoadingKey: string | null; lastError: string; activeDashboardView: AuroraDashboardViewId; panelLayout: AuroraPanelLayoutItem[];
  loadActiveDashboardView: () => void; applyDashboardViewPreset: (id: AuroraDashboardViewId) => void; loadPanelLayout: () => void; togglePanelVisibility: (id: AuroraPanelId) => void; togglePanelPinned: (id: AuroraPanelId) => void; movePanelUp: (id: AuroraPanelId) => void; movePanelDown: (id: AuroraPanelId) => void; resetPanelLayout: () => void; getVisiblePanelLayout: () => AuroraPanelLayoutItem[];
  setReminderTitle: (value: string) => void; setReminderDueAt: (value: string) => void; patchLocalSettingValue: (key: string, value: string) => void;
  loadDashboardIntelligence: () => Promise<void>; loadPlugins: () => Promise<void>; loadToolPermissions: () => Promise<void>; loadToolAudit: () => Promise<void>; loadSecurityPolicy: () => Promise<void>; loadReleaseCandidateStatus: () => Promise<void>; loadFrontendRefactorStatus: () => Promise<void>; loadDesktopShellStatus: () => Promise<void>; loadBackendSidecarStatus: () => Promise<void>; loadReminders: () => Promise<void>; loadNotificationEvents: () => Promise<void>; loadStartupBriefing: () => Promise<void>; loadUserSettingsProfile: () => Promise<void>;
  refreshAll: () => Promise<void>; updatePluginStatusFromStore: (key: string, enabled: boolean) => Promise<void>; applySecurityProfileFromStore: (key: string) => Promise<void>; freezeReleaseCandidateFromStore: () => Promise<void>; unfreezeReleaseCandidateFromStore: () => Promise<void>; generateReleaseCandidatePackageFromStore: () => Promise<void>; runStabilizationScanFromStore: (build?: boolean) => Promise<void>; saveStabilizationReportFromStore: (build?: boolean) => Promise<void>; runFrontendRefactorScanFromStore: () => Promise<void>; saveFrontendRefactorReportFromStore: () => Promise<void>; runBackendSidecarActionFromStore: (action: SidecarAction) => Promise<void>; createReminderFromStore: () => Promise<void>; updateReminderStatusFromStore: (id: number, status: string) => Promise<void>; updateUserSettingFromStore: (key: string, value: string) => Promise<void>; resetUserSettingsFromStore: () => Promise<void>;
};
const fail = (set: (state: Partial<Store>) => void, message: string) => set({ lastError: message });
export const useAuroraStore = create<Store>((set, get) => ({
  dashboardIntelligence: null, dashboardIntelligenceLoading: false, plugins: [], pluginMetrics: {}, pluginRegistryReport: "", pluginLoadingKey: null, toolPermissionMatrix: [], toolPermissionMetrics: {}, toolPermissionReport: "", toolAuditEvents: [], toolAuditMetrics: {}, toolAuditReport: "", securityProfiles: [], securityPolicyEvents: [], securityPolicyActive: {}, securityPolicyReport: "", securityPolicyLoadingKey: null, releaseCandidateStatus: null, releaseCandidatePackage: null, releaseCandidateLoading: false, stabilizationResult: null, stabilizationLoading: false, frontendRefactorResult: null, frontendRefactorLoading: false, desktopShellStatus: null, desktopShellLoading: false, backendSidecarStatus: null, backendSidecarLoading: false, reminders: [], notificationEvents: [], startupBriefing: null, reminderTitle: "", reminderDueAt: "tomorrow", reminderLoading: false, userSettingsProfile: null, settingsLoadingKey: null, lastError: "", activeDashboardView: "full-mission-control", panelLayout: [],
  loadActiveDashboardView: () => set({ activeDashboardView: loadActiveDashboardView() }),
  applyDashboardViewPreset: (id) => { const panelLayout = sortPanelLayout(createLayoutFromPreset(id)); savePanelLayoutToStorage(panelLayout); saveActiveDashboardView(id); set({ activeDashboardView: id, panelLayout }); },
  loadPanelLayout: () => set({ panelLayout: sortPanelLayout(loadPanelLayoutFromStorage()) }),
  togglePanelVisibility: (id) => { const layout = sortPanelLayout(get().panelLayout.map((item) => item.id === id ? { ...item, visible: !item.visible } : item)); savePanelLayoutToStorage(layout); set({ panelLayout: layout }); },
  togglePanelPinned: (id) => { const layout = sortPanelLayout(get().panelLayout.map((item) => item.id === id ? { ...item, pinned: !item.pinned } : item)); savePanelLayoutToStorage(layout); set({ panelLayout: layout }); },
  movePanelUp: (id) => { const layout = sortPanelLayout(get().panelLayout.map((item) => ({ ...item }))); const index = layout.findIndex((item) => item.id === id); if (index <= 0) return; [layout[index].order, layout[index - 1].order] = [layout[index - 1].order, layout[index].order]; const next = sortPanelLayout(layout); savePanelLayoutToStorage(next); set({ panelLayout: next }); },
  movePanelDown: (id) => { const layout = sortPanelLayout(get().panelLayout.map((item) => ({ ...item }))); const index = layout.findIndex((item) => item.id === id); if (index < 0 || index >= layout.length - 1) return; [layout[index].order, layout[index + 1].order] = [layout[index + 1].order, layout[index].order]; const next = sortPanelLayout(layout); savePanelLayoutToStorage(next); set({ panelLayout: next }); },
  resetPanelLayout: () => { const panelLayout = sortPanelLayout(resetPanelLayoutStorage()); saveActiveDashboardView("full-mission-control"); set({ activeDashboardView: "full-mission-control", panelLayout }); },
  getVisiblePanelLayout: () => sortPanelLayout(get().panelLayout).filter((item) => item.visible),
  setReminderTitle: (reminderTitle) => set({ reminderTitle }), setReminderDueAt: (reminderDueAt) => set({ reminderDueAt }),
  patchLocalSettingValue: (key, value) => set((s) => !s.userSettingsProfile ? s : { userSettingsProfile: { ...s.userSettingsProfile, settings: s.userSettingsProfile.settings.map((item) => item.key === key ? { ...item, value } : item) } }),
  loadDashboardIntelligence: async () => { set({ dashboardIntelligenceLoading: true }); try { set({ dashboardIntelligence: await getDashboardIntelligence(), lastError: "" }); } catch { fail(set, "Failed to load dashboard intelligence."); } finally { set({ dashboardIntelligenceLoading: false }); } },
  loadPlugins: async () => { try { const d = await getPlugins(); set({ plugins: d.plugins || [], pluginMetrics: d.metrics || {}, pluginRegistryReport: d.report || "" }); } catch { fail(set, "Failed to load plugins."); } },
  loadToolPermissions: async () => { try { const d = await getToolPermissions(); set({ toolPermissionMatrix: d.matrix || [], toolPermissionMetrics: d.metrics || {}, toolPermissionReport: d.report || "" }); } catch { fail(set, "Failed to load tool permissions."); } },
  loadToolAudit: async () => { try { const d = await getToolAudit(); set({ toolAuditEvents: d.events || [], toolAuditMetrics: d.metrics || {}, toolAuditReport: d.report || "" }); } catch { fail(set, "Failed to load tool audit."); } },
  loadSecurityPolicy: async () => { try { const d = await getSecurityPolicy(); set({ securityProfiles: d.profiles || [], securityPolicyEvents: d.events || [], securityPolicyActive: d.active_policy || {}, securityPolicyReport: d.report || "" }); } catch { fail(set, "Failed to load security policy."); } },
  loadReleaseCandidateStatus: async () => { try { set({ releaseCandidateStatus: await getReleaseCandidateStatus() }); } catch { fail(set, "Failed to load release candidate status."); } },
  loadFrontendRefactorStatus: async () => { set({ frontendRefactorLoading: true }); try { set({ frontendRefactorResult: await getFrontendRefactorStatus() }); } catch { fail(set, "Failed to load frontend refactor status."); } finally { set({ frontendRefactorLoading: false }); } },
  loadDesktopShellStatus: async () => { set({ desktopShellLoading: true }); try { set({ desktopShellStatus: await getDesktopShellStatus() }); } catch { fail(set, "Failed to load desktop shell status."); } finally { set({ desktopShellLoading: false }); } },
  loadBackendSidecarStatus: async () => { set({ backendSidecarLoading: true }); try { set({ backendSidecarStatus: await getBackendSidecarStatus() }); } catch { fail(set, "Failed to load backend sidecar status."); } finally { set({ backendSidecarLoading: false }); } },
  loadReminders: async () => { try { set({ reminders: (await getReminders()).reminders || [] }); } catch { fail(set, "Failed to load reminders."); } }, loadNotificationEvents: async () => { try { set({ notificationEvents: (await getNotificationEvents()).events || [] }); } catch { fail(set, "Failed to load notification events."); } }, loadStartupBriefing: async () => { try { set({ startupBriefing: await getStartupBriefing() }); } catch { fail(set, "Failed to load startup briefing."); } }, loadUserSettingsProfile: async () => { try { set({ userSettingsProfile: await getUserSettingsProfile() }); } catch { fail(set, "Failed to load user settings."); } },
  refreshAll: async () => { await Promise.allSettled([get().loadDashboardIntelligence(), get().loadPlugins(), get().loadToolPermissions(), get().loadToolAudit(), get().loadSecurityPolicy(), get().loadReleaseCandidateStatus(), get().loadFrontendRefactorStatus(), get().loadDesktopShellStatus(), get().loadBackendSidecarStatus(), get().loadReminders(), get().loadNotificationEvents(), get().loadStartupBriefing(), get().loadUserSettingsProfile()]); },
  updatePluginStatusFromStore: async (key, enabled) => { set({ pluginLoadingKey: key }); try { await updatePluginStatus(key, enabled); await Promise.all([get().loadPlugins(), get().loadToolPermissions(), get().loadToolAudit(), get().loadDashboardIntelligence()]); } finally { set({ pluginLoadingKey: null }); } }, applySecurityProfileFromStore: async (key) => { set({ securityPolicyLoadingKey: key }); try { await applySecurityProfile(key); await get().refreshAll(); } finally { set({ securityPolicyLoadingKey: null }); } },
  freezeReleaseCandidateFromStore: async () => { set({ releaseCandidateLoading: true }); try { await freezeReleaseCandidate("Preparing O.R.I.O.N. v4.5 release candidate."); await get().refreshAll(); } finally { set({ releaseCandidateLoading: false }); } }, unfreezeReleaseCandidateFromStore: async () => { set({ releaseCandidateLoading: true }); try { await unfreezeReleaseCandidate("Release candidate freeze lifted by user."); await get().refreshAll(); } finally { set({ releaseCandidateLoading: false }); } }, generateReleaseCandidatePackageFromStore: async () => { set({ releaseCandidateLoading: true }); try { set({ releaseCandidatePackage: await generateReleaseCandidatePackage() }); await get().loadReleaseCandidateStatus(); } finally { set({ releaseCandidateLoading: false }); } },
  runStabilizationScanFromStore: async (build = false) => { set({ stabilizationLoading: true }); try { set({ stabilizationResult: await runStabilizationScan(build) }); } finally { set({ stabilizationLoading: false }); } }, saveStabilizationReportFromStore: async (build = false) => { set({ stabilizationLoading: true }); try { set({ stabilizationResult: await saveStabilizationReport(build) }); } finally { set({ stabilizationLoading: false }); } }, runFrontendRefactorScanFromStore: async () => get().loadFrontendRefactorStatus(), saveFrontendRefactorReportFromStore: async () => { set({ frontendRefactorLoading: true }); try { set({ frontendRefactorResult: await saveFrontendRefactorReport() }); } finally { set({ frontendRefactorLoading: false }); } },
  runBackendSidecarActionFromStore: async (action) => { set({ backendSidecarLoading: true }); try { set({ backendSidecarStatus: (await runBackendSidecarAction(action)).sidecar }); } finally { set({ backendSidecarLoading: false }); } }, createReminderFromStore: async () => { const { reminderTitle, reminderDueAt } = get(); if (!reminderTitle.trim()) return fail(set, "Reminder title is required."); set({ reminderLoading: true }); try { await createReminder({ title: reminderTitle.trim(), description: "Created from Aurora OS.", due_at: reminderDueAt || "tomorrow", priority: "medium" }); set({ reminderTitle: "" }); await Promise.all([get().loadReminders(), get().loadNotificationEvents()]); } finally { set({ reminderLoading: false }); } }, updateReminderStatusFromStore: async (id, status) => { await updateReminderStatus(id, status); await Promise.all([get().loadReminders(), get().loadNotificationEvents()]); }, updateUserSettingFromStore: async (key, value) => { set({ settingsLoadingKey: key }); try { await updateUserSetting(key, value); await get().loadUserSettingsProfile(); } finally { set({ settingsLoadingKey: null }); } }, resetUserSettingsFromStore: async () => { set({ settingsLoadingKey: "reset" }); try { await resetUserSettings(); await get().loadUserSettingsProfile(); } finally { set({ settingsLoadingKey: null }); } },
}));
