"use client";
import { useEffect } from "react";
import { GitBranch } from "lucide-react";
import { useProjectStore } from "@/store/project-store";
import { useUiStore } from "@/store/ui-store";
import { TaskColumn } from "@/lib/project-types";
import { GlassPanel } from "../aurora/glass-panel";
import { StatusChip } from "../aurora/status-chip";
const tabs = ["Overview", "Tasks", "Files", "Missions", "Deployments", "Logs"];
const columns: TaskColumn[] = ["Ideas", "Planning", "In Progress", "Testing", "Completed"];
export function ProjectWorkspace() {
 const { projects, selectedId, activeTab, selectProject, setActiveTab, moveTask } = useProjectStore(); const selected = projects.find((p) => p.id === selectedId) || projects[0]; const setOrbState = useUiStore((s) => s.setOrbState); useEffect(() => setOrbState(projects.some((p) => p.status === "Active") ? "executing" : "idle"), [projects, setOrbState]);
 return <div className="grid gap-4 xl:grid-cols-[320px_minmax(0,1fr)]"><div className="space-y-3">{projects.map((project) => <button key={project.id} onClick={() => selectProject(project.id)} className={`w-full rounded-[16px] border p-4 text-left ${project.id === selected.id ? "border-[#61DFFF]/40 bg-[#4F8BFF]/15" : "border-white/10 bg-[#11151D]/75"}`}><p className="font-black text-white">{project.name}</p><p className="mt-1 text-sm text-slate-400">{project.tagline}</p><div className="mt-3 h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-[#18E299]" style={{ width: `${project.progress}%` }}/></div></button>)}</div><div className="space-y-4"><GlassPanel className="p-5"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-3xl font-black text-white">{selected.name}</h1><p className="mt-2 text-slate-400">{selected.description}</p></div><StatusChip tone="success">{selected.status}</StatusChip></div><div className="mt-4 flex flex-wrap gap-2 text-sm text-slate-400"><GitBranch size={16}/> {selected.repository} · {selected.branch} · updated {selected.updated}</div><div className="mt-5 grid gap-3 md:grid-cols-4"><Metric label="Progress" value={`${selected.progress}%`}/><Metric label="Health" value={`${selected.health}%`}/><Metric label="Memories" value={String(selected.memories)}/><Metric label="Priority" value={selected.priority}/></div></GlassPanel><div className="flex flex-wrap gap-2">{tabs.map((tab) => <button key={tab} onClick={() => setActiveTab(tab)} className={`rounded-xl border px-3 py-2 text-sm ${activeTab === tab ? "border-[#61DFFF]/40 bg-[#61DFFF]/10 text-white" : "border-white/10 text-slate-400"}`}>{tab}</button>)}</div><GlassPanel className="overflow-x-auto p-4"><div className="grid min-w-[900px] grid-cols-5 gap-3">{columns.map((column) => <div key={column} className="rounded-2xl border border-white/10 bg-black/20 p-3"><h3 className="font-bold text-white">{column}</h3><div className="mt-3 space-y-2">{selected.tasks.filter((task) => task.column === column).map((task) => <div key={task.id} className="rounded-xl border border-white/10 bg-[#11151D] p-3 text-sm"><p className="text-slate-200">{task.title}</p><p className="mt-1 text-xs text-slate-500">{task.owner}</p><button onClick={() => moveTask(selected.id, task.id)} className="mt-3 rounded-lg bg-[#4F8BFF]/15 px-2 py-1 text-xs text-blue-200">Move</button></div>)}</div></div>)}</div></GlassPanel><GlassPanel className="p-5"><h2 className="font-black text-white">Project Detail Panel</h2><div className="mt-3 grid gap-3 md:grid-cols-3"><List title="Files" items={selected.files}/><List title="Missions" items={selected.missions}/><List title="Next Actions" items={selected.nextActions}/></div></GlassPanel></div></div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/10 bg-black/20 p-3"><p className="text-xs text-slate-500">{label}</p><p className="font-black text-white">{value}</p></div>; } function List({ title, items }: { title: string; items: string[] }) { return <div><p className="font-bold text-white">{title}</p>{items.map((item) => <p className="mt-2 text-sm text-slate-400" key={item}>• {item}</p>)}</div>; }
