import type { DemoWalkthroughState } from "@/types/demo";
import { ORION_DEMO_WALKTHROUGH_STEPS } from "@/lib/demoWalkthroughRegistry";
import { GlassPanel } from "@/components/aurora/ui/GlassPanel";
import { StatusPill } from "@/components/aurora/ui/StatusPill";

type Props = { demoWalkthroughState: DemoWalkthroughState; onStart: () => void; onStop: () => void; onNext: () => void; onPrevious: () => void; onReset: () => void; };
export function GuidedWalkthroughPanel({ demoWalkthroughState, onStart, onStop, onNext, onPrevious, onReset }: Props) {
  const currentStep = ORION_DEMO_WALKTHROUGH_STEPS[demoWalkthroughState.currentStepIndex] || ORION_DEMO_WALKTHROUGH_STEPS[0];
  const progress = ((demoWalkthroughState.currentStepIndex + 1) / ORION_DEMO_WALKTHROUGH_STEPS.length) * 100;
  return <GlassPanel title="Guided Portfolio Walkthrough" subtitle="Step-by-step demo sequence for presenting O.R.I.O.N. Aurora OS" version="v5.3"><div className="space-y-4 rounded-2xl border border-white/10 bg-black/30 p-4"><div className="rounded-2xl border border-cyan-400/20 bg-cyan-500/10 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.25em] text-cyan-300">Current Step</p><h3 className="mt-3 text-2xl font-black text-slate-100">{currentStep.stepNumber}. {currentStep.title}</h3><p className="mt-2 text-sm text-slate-300">{currentStep.subtitle}</p></div><StatusPill tone={demoWalkthroughState.enabled ? "success" : "default"}>{demoWalkthroughState.enabled ? "active" : "idle"}</StatusPill></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-black/40"><div className="h-full rounded-full bg-cyan-300" style={{ width: `${progress}%` }} /></div><p className="mt-3 text-xs text-slate-400">Step {demoWalkthroughState.currentStepIndex + 1} of {ORION_DEMO_WALKTHROUGH_STEPS.length}</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xs uppercase tracking-[0.25em] text-cyan-300">Demo Callout</p><p className="mt-3 text-sm leading-7 text-slate-300">{currentStep.callout}</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xs uppercase tracking-[0.25em] text-cyan-300">Talking Points</p><div className="mt-3 space-y-2">{currentStep.talkingPoints.map((point) => <p key={point} className="rounded-xl border border-white/10 bg-black/30 p-3 text-xs leading-5 text-slate-300">{point}</p>)}</div></div><div className="grid grid-cols-5 gap-2"><button onClick={onStart} className="rounded-2xl bg-cyan-300 px-3 py-3 text-xs font-bold text-slate-950 transition hover:bg-cyan-200">Start</button><button onClick={onPrevious} className="rounded-2xl border border-violet-400/30 px-3 py-3 text-xs font-bold text-violet-200 transition hover:bg-violet-500/10">Prev</button><button onClick={onNext} className="rounded-2xl border border-emerald-400/30 px-3 py-3 text-xs font-bold text-emerald-200 transition hover:bg-emerald-500/10">Next</button><button onClick={onStop} className="rounded-2xl border border-yellow-400/30 px-3 py-3 text-xs font-bold text-yellow-200 transition hover:bg-yellow-500/10">Stop</button><button onClick={onReset} className="rounded-2xl border border-red-400/30 px-3 py-3 text-xs font-bold text-red-200 transition hover:bg-red-500/10">Reset</button></div><p className="text-xs leading-5 text-slate-500">Safety: the walkthrough only changes dashboard views and presentation state. It does not execute tools.</p></div></GlassPanel>;
}
