import type { ReleaseCandidatePackage, ReleaseCandidateStatus } from "@/types/orion";
import { GlassPanel } from "@/components/aurora/ui/GlassPanel";
import { MetricCard } from "@/components/aurora/ui/MetricCard";
import { StatusPill } from "@/components/aurora/ui/StatusPill";

export function ReleaseCandidatePanel({ status, latestPackage, loading, message, runAction }: {
  status: ReleaseCandidateStatus | null; latestPackage: ReleaseCandidatePackage | null; loading: boolean; message: string;
  runAction: (action: "freeze" | "unfreeze" | "package") => void;
}) {
  return <GlassPanel className="border-cyan-400/20 bg-white/[0.06] p-5">
    <div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-bold text-white">Release Candidate</h2><p className="text-sm text-slate-400">v4.3 system freeze, release checklist, diagnostics export, and demo package</p></div><span className="rounded-full border border-cyan-400/30 px-3 py-1 text-xs text-cyan-300">v4.3</span></div>
    <div className="space-y-4 rounded-2xl border border-white/10 bg-black/30 p-4">{!status ? <p className="text-sm text-slate-500">Release Candidate status has not loaded yet.</p> : <>
      <div className={`rounded-2xl border p-4 ${status.freeze_state.frozen ? "border-cyan-400/30 bg-cyan-500/10 text-cyan-200" : "border-yellow-400/30 bg-yellow-500/10 text-yellow-200"}`}><p className="text-xs uppercase tracking-[0.25em]">System Freeze</p><div className="mt-3 flex items-end justify-between gap-3"><span className="text-3xl font-black">{status.freeze_state.frozen ? "FROZEN" : "OPEN"}</span><span className="text-xs uppercase tracking-[0.2em]">{status.freeze_state.release_version}</span></div><p className="mt-3 text-xs leading-5">{status.freeze_state.freeze_reason || "No freeze reason recorded."}</p></div>
      <div className="grid grid-cols-2 gap-2"><MetricCard label="Checklist Passed" value={status.checklist.passed} /><MetricCard label="Checklist Failed" value={status.checklist.failed} /></div>
      <div className="grid grid-cols-3 gap-2"><button onClick={() => runAction("freeze")} disabled={loading} className="rounded-2xl bg-cyan-300 px-4 py-3 text-sm font-bold text-slate-950 transition hover:bg-cyan-200 disabled:opacity-60">Freeze</button><button onClick={() => runAction("unfreeze")} disabled={loading} className="rounded-2xl border border-yellow-400/30 px-4 py-3 text-sm font-bold text-yellow-200 transition hover:bg-yellow-500/10 disabled:opacity-60">Unfreeze</button><button onClick={() => runAction("package")} disabled={loading} className="rounded-2xl border border-violet-400/30 px-4 py-3 text-sm font-bold text-violet-200 transition hover:bg-violet-500/10 disabled:opacity-60">Package</button></div>
      <div className="max-h-72 space-y-2 overflow-y-auto rounded-2xl border border-white/10 bg-white/5 p-3"><p className="text-xs uppercase tracking-[0.25em] text-cyan-300">Release Checklist</p>{status.checklist.items.map((item) => <div key={item.item} className="rounded-xl border border-white/10 bg-black/30 p-3"><div className="flex items-start justify-between gap-3"><p className="text-sm font-semibold text-slate-100">{item.item}</p><StatusPill tone={item.ok ? "success" : "danger"}>{item.ok ? "pass" : "fail"}</StatusPill></div><p className="mt-2 text-xs text-slate-500">{item.details}</p></div>)}</div>
      {latestPackage && <div className="rounded-2xl border border-violet-400/20 bg-violet-500/10 p-3"><p className="text-xs uppercase tracking-[0.25em] text-violet-200">Latest Package</p><p className="mt-2 break-all text-xs leading-5 text-slate-300">{latestPackage.summary_path}</p></div>}
      <details className="rounded-2xl border border-white/10 bg-white/5 p-3"><summary className="cursor-pointer text-sm font-semibold text-cyan-200">Release Candidate Report</summary><pre className="mt-3 max-h-96 overflow-y-auto whitespace-pre-wrap text-xs leading-5 text-slate-300">{status.report}</pre></details>
    </>}{message && <p className="rounded-xl border border-cyan-400/20 bg-cyan-500/10 p-3 text-sm text-cyan-100">{message}</p>}<p className="text-xs leading-5 text-slate-500">Safety: System Freeze is local release-readiness mode. It does not publish, push, delete, or bypass approvals.</p></div>
  </GlassPanel>;
}
