import type { StabilizationResult } from "@/types/orion";
import { GlassPanel } from "@/components/aurora/ui/GlassPanel";

export function StabilizationPanel({ result, loading, message, runAction }: {
  result: StabilizationResult | null; loading: boolean; message: string;
  runAction: (action: "scan" | "save", runBuild?: boolean) => void;
}) {
  const statusClass = result?.status === "stable" ? "border-emerald-400/30 bg-emerald-500/10 text-emerald-200" : result?.status === "needs_attention" ? "border-red-400/30 bg-red-500/10 text-red-200" : "border-yellow-400/30 bg-yellow-500/10 text-yellow-200";
  return <GlassPanel className="border-cyan-400/20 bg-white/[0.06] p-5">
    <div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-bold text-white">Stabilization Manager</h2><p className="text-sm text-slate-400">v4.2 codebase cleanup, import checks, compile scan, and release hardening</p></div><span className="rounded-full border border-cyan-400/30 px-3 py-1 text-xs text-cyan-300">v4.2</span></div>
    <div className="space-y-4 rounded-2xl border border-white/10 bg-black/30 p-4"><div className="grid grid-cols-3 gap-2"><button onClick={() => runAction("scan")} disabled={loading} className="rounded-2xl bg-cyan-300 px-4 py-3 text-sm font-bold text-slate-950 transition hover:bg-cyan-200 disabled:opacity-60">Scan</button><button onClick={() => runAction("scan", true)} disabled={loading} className="rounded-2xl border border-violet-400/30 px-4 py-3 text-sm font-bold text-violet-200 transition hover:bg-violet-500/10 disabled:opacity-60">Scan + Build</button><button onClick={() => runAction("save")} disabled={loading} className="rounded-2xl border border-emerald-400/30 px-4 py-3 text-sm font-bold text-emerald-200 transition hover:bg-emerald-500/10 disabled:opacity-60">Save Report</button></div>
      {!result ? <p className="text-sm text-slate-500">Run a stabilization scan to inspect the codebase.</p> : <><div className={`rounded-2xl border p-4 ${statusClass}`}><p className="text-xs uppercase tracking-[0.25em]">Stabilization Status</p><div className="mt-3 flex items-end justify-between gap-3"><span className="text-3xl font-black">{result.status}</span><span className="text-xs uppercase tracking-[0.2em]">{result.generated_at}</span></div>{result.path && <p className="mt-3 break-all text-xs leading-5">Saved: {result.path}</p>}</div><details className="rounded-2xl border border-white/10 bg-white/5 p-3"><summary className="cursor-pointer text-sm font-semibold text-cyan-200">Stabilization Report</summary><pre className="mt-3 max-h-96 overflow-y-auto whitespace-pre-wrap text-xs leading-5 text-slate-300">{result.report}</pre></details></>}
      {message && <p className="rounded-xl border border-cyan-400/20 bg-cyan-500/10 p-3 text-sm text-cyan-100">{message}</p>}<p className="text-xs leading-5 text-slate-500">Safety: v4.2 continues scan/report-only stabilization. It does not delete, rewrite, or auto-clean files.</p></div>
  </GlassPanel>;
}
