#!/usr/bin/env python3
"""Generate and verify active O.R.I.O.N. version surfaces from one manifest."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "release-manifest.json"
SEMVER = re.compile(r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$")


def load_manifest() -> dict[str, object]:
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    required = {
        "schemaVersion": int,
        "product": str,
        "productName": str,
        "interface": str,
        "version": str,
        "channel": str,
        "releaseName": str,
    }
    for key, expected_type in required.items():
        value = manifest.get(key)
        if not isinstance(value, expected_type) or (
            isinstance(value, str) and not value.strip()
        ):
            raise ValueError(f"release-manifest.json requires {key}: {expected_type.__name__}")
    if not SEMVER.fullmatch(str(manifest["version"])):
        raise ValueError("release-manifest.json version must be semantic X.Y.Z")
    return manifest


def render_json(path: Path, update) -> str:
    payload = json.loads(path.read_text(encoding="utf-8"))
    update(payload)
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def replace_package_version(source: str, version: str) -> str:
    package_start = source.find("[package]")
    package_end = source.find("\n[", package_start + 1)
    if package_start < 0 or package_end < 0:
        raise ValueError("Cargo.toml is missing its [package] section")
    package = source[package_start:package_end]
    updated, count = re.subn(
        r'(?m)^version = "[^"]+"$', f'version = "{version}"', package, count=1
    )
    if count != 1:
        raise ValueError("Cargo.toml is missing the package version")
    return source[:package_start] + updated + source[package_end:]


def replace_lock_version(source: str, version: str) -> str:
    updated, count = re.subn(
        r'(\[\[package\]\]\nname = "orion-aurora-os"\nversion = ")[^"]+("\n)',
        rf"\g<1>{version}\g<2>",
        source,
        count=1,
    )
    if count != 1:
        raise ValueError("Cargo.lock is missing the orion-aurora-os package")
    return updated


def generated_python(manifest: dict[str, object]) -> str:
    return f'''"""Generated by scripts/sync_release_manifest.py; do not edit."""

PRODUCT = {manifest["product"]!r}
PRODUCT_NAME = {manifest["productName"]!r}
INTERFACE_NAME = {manifest["interface"]!r}
VERSION = {manifest["version"]!r}
VERSION_LABEL = "v" + VERSION
RELEASE_CHANNEL = {manifest["channel"]!r}
RELEASE_NAME = {manifest["releaseName"]!r}
'''


def generated_typescript(manifest: dict[str, object]) -> str:
    fields = {
        "product": manifest["product"],
        "productName": manifest["productName"],
        "interface": manifest["interface"],
        "version": manifest["version"],
        "versionLabel": f'v{manifest["version"]}',
        "channel": manifest["channel"],
        "releaseName": manifest["releaseName"],
    }
    lines = ["// Generated by scripts/sync_release_manifest.py; do not edit.", "export const ORION_BUILD = {"]
    lines.extend(
        f"  {key}: {json.dumps(value, ensure_ascii=False)}," for key, value in fields.items()
    )
    lines.extend(["} as const;", ""])
    return "\n".join(lines)


def render_readme(source: str, version: str) -> str:
    replacements = (
        (
            r"(img\.shields\.io/badge/version-v)[0-9]+\.[0-9]+\.[0-9]+",
            rf"\g<1>{version}",
        ),
        (
            r"(active product version is \*\*O\.R\.I\.O\.N\. v)[0-9]+\.[0-9]+\.[0-9]+(\*\*)",
            rf"\g<1>{version}\g<2>",
        ),
        (
            r"(\| Current version \| v)[0-9]+\.[0-9]+\.[0-9]+( — generated from `release-manifest\.json` \|)",
            rf"\g<1>{version}\g<2>",
        ),
    )
    rendered = source
    for pattern, replacement in replacements:
        rendered, count = re.subn(pattern, replacement, rendered, count=1)
        if count != 1:
            raise ValueError(f"README.md is missing its generated version marker: {pattern}")
    return rendered


def expected_outputs(manifest: dict[str, object]) -> dict[Path, str]:
    version = str(manifest["version"])
    package_json = ROOT / "frontend/package.json"
    package_lock = ROOT / "frontend/package-lock.json"
    tauri_config = ROOT / "frontend/src-tauri/tauri.conf.json"
    cargo_toml = ROOT / "frontend/src-tauri/Cargo.toml"
    cargo_lock = ROOT / "frontend/src-tauri/Cargo.lock"
    readme = ROOT / "README.md"

    return {
        package_json: render_json(
            package_json, lambda payload: payload.__setitem__("version", version)
        ),
        package_lock: render_json(
            package_lock,
            lambda payload: (
                payload.__setitem__("version", version),
                payload["packages"][""].__setitem__("version", version),
            ),
        ),
        tauri_config: render_json(
            tauri_config, lambda payload: payload.__setitem__("version", version)
        ),
        cargo_toml: replace_package_version(
            cargo_toml.read_text(encoding="utf-8"), version
        ),
        cargo_lock: replace_lock_version(
            cargo_lock.read_text(encoding="utf-8"), version
        ),
        ROOT / "backend/core/version.py": generated_python(manifest),
        ROOT / "frontend/src/lib/orion-build.ts": generated_typescript(manifest),
        readme: render_readme(readme.read_text(encoding="utf-8"), version),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="Fail instead of updating stale surfaces."
    )
    arguments = parser.parse_args()
    manifest = load_manifest()
    mismatches: list[str] = []

    for path, expected in expected_outputs(manifest).items():
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current == expected:
            continue
        relative = path.relative_to(ROOT).as_posix()
        if arguments.check:
            mismatches.append(relative)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
            print(f"Updated {relative}")

    if mismatches:
        print("Release manifest mismatch:")
        for path in mismatches:
            print(f"- {path}")
        print("Run: python3 scripts/sync_release_manifest.py")
        return 1

    print(f"O.R.I.O.N. version surfaces match {manifest['version']}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
