"use client";

import { FormEvent, useMemo, useState } from "react";
import { CheckCircle2, ChevronRight, CircleDot, LockKeyhole, Play, Plus, RotateCcw, Save, Search, Server, ShieldCheck, TerminalSquare, Workflow } from "lucide-react";
import { GlassPanel } from "./glass-panel";

const fieldClass = "w-full rounded-xl border border-white/[0.09] bg-black/25 px-3 py-2.5 text-sm text-slate-100 outline-none transition placeholder:text-slate-600 focus:border-cyan-300/35";
const buttonClass = "inline-flex items-center justify-center gap-2 rounded-xl border border-cyan-300/20 bg-cyan-300/[0.08] px-3.5 py-2.5 text-xs font-bold text-cyan-100 transition hover:bg-cyan-300/[0.14]";

function WorkspaceHeader({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <header className="mb-6"><p className="text-[10px] font-bold uppercase tracking-[0.28em] text-cyan-300">{eyebrow}</p><h1 className="mt-2 text-2xl font-black text-white sm:text-3xl">{title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">{description}</p></header>;
}

function Toggle({ label, detail, initial = false }: { label: string; detail: string; initial?: boolean }) {
  const [enabled, setEnabled] = useState(initial);
  return <button type="button" onClick={() => setEnabled(!enabled)} className="flex w-full items-center gap-3 rounded-xl border border-white/[0.07] bg-white/[0.025] p-3 text-left"><span className={`relative h-6 w-11 shrink-0 rounded-full transition ${enabled ? "bg-cyan-300" : "bg-slate-700"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-slate-950 transition ${enabled ? "left-6" : "left-1"}`} /></span><span><span className="block text-sm font-semibold text-slate-100">{label}</span><span className="mt-0.5 block text-xs text-slate-500">{detail}</span></span></button>;
}

export function SettingsWorkspace() {
  const [saved, setSaved] = useState(false);
  const save = (event: FormEvent) => { event.preventDefault(); setSaved(true); window.setTimeout(() => setSaved(false), 1800); };
  return <div><WorkspaceHeader eyebrow="Personal control plane" title="Settings" description="Configure your identity, assistant behaviour, notifications, appearance, model preferences and privacy from one workspace." /><form onSubmit={save} className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><div className="space-y-5"><GlassPanel className="p-5"><h2 className="font-bold text-white">Profile & assistant</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-xs text-slate-400">Display name<input className={`${fieldClass} mt-2`} defaultValue="Wichel Ashford" /></label><label className="text-xs text-slate-400">Preferred model<select className={`${fieldClass} mt-2`} defaultValue="Auto"><option>Auto</option><option>Reasoning</option><option>Fast</option><option>Local</option></select></label><label className="text-xs text-slate-400 sm:col-span-2">Assistant instructions<textarea className={`${fieldClass} mt-2 min-h-24 resize-y`} defaultValue="Be concise, proactive and safety-aware." /></label></div></GlassPanel><GlassPanel className="p-5"><h2 className="font-bold text-white">Interface</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Toggle label="Compact metrics" detail="Fit more telemetry on screen." /><Toggle label="Reduced motion" detail="Minimise interface animations." /><Toggle label="Context rail" detail="Show mission context by default." initial /><Toggle label="24-hour time" detail="Use operational time format." initial /></div></GlassPanel></div><div className="space-y-5"><GlassPanel className="p-5"><h2 className="font-bold text-white">Notifications</h2><div className="mt-4 space-y-3"><Toggle label="Mission events" detail="Completion and failure alerts." initial /><Toggle label="Security alerts" detail="High-risk action notifications." initial /><Toggle label="Desktop notifications" detail="Notify outside the active window." /></div></GlassPanel><GlassPanel className="p-5"><h2 className="font-bold text-white">Data & privacy</h2><div className="mt-4 space-y-3"><Toggle label="Remember context" detail="Retain approved assistant context." initial /><Toggle label="Anonymous diagnostics" detail="Share local reliability metrics." /></div><button type="button" className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-rose-300"><RotateCcw size={14} /> Reset local preferences</button></GlassPanel><button className={`${buttonClass} w-full`}><Save size={15} />{saved ? "Settings saved" : "Save settings"}</button></div></form></div>;
}

export function SystemWorkspace() {
  const services = [["API gateway", "Healthy", "18 ms"], ["Mission runtime", "Healthy", "42 ms"], ["Vector memory", "Ready", "12 indexes"], ["Desktop sidecar", "Standby", "Local"]];
  return <div><WorkspaceHeader eyebrow="Runtime operations" title="System" description="Inspect service health, runtime capacity, connectivity and deployment information." /><div className="grid gap-5 lg:grid-cols-3"><GlassPanel className="p-5 lg:col-span-2"><div className="flex items-center justify-between"><h2 className="font-bold text-white">Services</h2><button className={buttonClass}><RotateCcw size={14} /> Refresh</button></div><div className="mt-4 space-y-2">{services.map(([name, status, meta]) => <div key={name} className="grid grid-cols-[1fr_auto_auto] items-center gap-4 rounded-xl border border-white/[0.07] bg-white/[0.025] p-3"><span className="flex items-center gap-2 text-sm font-semibold text-slate-200"><Server size={15} className="text-cyan-300" />{name}</span><span className="text-xs text-emerald-300">{status}</span><span className="w-20 text-right text-xs text-slate-500">{meta}</span></div>)}</div></GlassPanel><GlassPanel className="p-5"><h2 className="font-bold text-white">Capacity</h2><div className="mt-5 space-y-5">{[["CPU", 34], ["Memory", 58], ["Storage", 41]].map(([label, value]) => <div key={String(label)}><div className="mb-2 flex justify-between text-xs"><span className="text-slate-400">{label}</span><span className="text-slate-200">{value}%</span></div><div className="h-2 rounded-full bg-white/[0.06]"><div className="h-2 rounded-full bg-gradient-to-r from-cyan-400 to-violet-400" style={{ width: `${value}%` }} /></div></div>)}</div></GlassPanel></div></div>;
}

export function SecurityWorkspace() {
  return <div><WorkspaceHeader eyebrow="Trust & governance" title="Security" description="Review the active protection profile, approval boundaries, access posture and recent security decisions." /><div className="grid gap-5 lg:grid-cols-2"><GlassPanel className="p-5"><div className="flex items-center gap-3"><div className="rounded-2xl bg-emerald-400/10 p-3 text-emerald-300"><ShieldCheck /></div><div><p className="font-bold text-white">Strict protection active</p><p className="text-xs text-slate-500">All elevated actions require approval</p></div></div><div className="mt-5 space-y-3"><Toggle label="Approval gate" detail="Confirm destructive and external actions." initial /><Toggle label="Credential redaction" detail="Mask secrets in logs and reports." initial /><Toggle label="Plugin isolation" detail="Restrict untrusted plugin permissions." initial /></div></GlassPanel><GlassPanel className="p-5"><h2 className="font-bold text-white">Access review</h2><div className="mt-4 space-y-3">{[["API credentials", "Protected"], ["Desktop control", "Approval required"], ["Network tools", "Restricted"], ["Audit retention", "Enabled"]].map(([label, value]) => <div key={label} className="flex items-center justify-between rounded-xl border border-white/[0.07] p-3 text-sm"><span className="flex items-center gap-2 text-slate-300"><LockKeyhole size={14} className="text-violet-300" />{label}</span><span className="text-xs text-emerald-300">{value}</span></div>)}</div></GlassPanel></div></div>;
}

export function WorkflowsWorkspace() {
  const [runs, setRuns] = useState(3);
  const workflows = useMemo(() => [["Release readiness", "8 steps", "Validated"], ["Research brief", "5 steps", "Ready"], ["Workspace diagnosis", "6 steps", "Draft"]], []);
  return <div><WorkspaceHeader eyebrow="Automation studio" title="Workflows" description="Create, inspect and run reusable orchestration blueprints with visible safety gates and execution state." /><div className="mb-5 flex flex-wrap gap-3"><button className={buttonClass}><Plus size={14} /> New workflow</button><button className={buttonClass}><Search size={14} /> Browse templates</button><span className="ml-auto self-center text-xs text-slate-500">{runs} runs this session</span></div><div className="grid gap-4 lg:grid-cols-3">{workflows.map(([name, steps, state], index) => <GlassPanel key={name} className="p-5"><div className="flex items-start justify-between"><Workflow className="text-cyan-300" /><span className="rounded-full bg-emerald-400/10 px-2 py-1 text-[10px] font-bold text-emerald-300">{state}</span></div><h2 className="mt-5 font-bold text-white">{name}</h2><p className="mt-1 text-xs text-slate-500">{steps} · {index + 1} approval gate</p><div className="mt-5 flex items-center gap-2"><button onClick={() => setRuns((value) => value + 1)} className={buttonClass}><Play size={13} /> Run</button><button className="rounded-xl p-2.5 text-slate-400 hover:bg-white/[0.05]"><ChevronRight size={16} /></button></div></GlassPanel>)}</div></div>;
}

export function ConsoleWorkspace() {
  const [command, setCommand] = useState(""); const [lines, setLines] = useState(["O.R.I.O.N. console v6.7", "Runtime connected · strict safety profile", "Type `help` to list local commands."]);
  const execute = (event: FormEvent) => { event.preventDefault(); if (!command.trim()) return; setLines((current) => [...current, `› ${command}`, command === "status" ? "All monitored services are healthy." : "Command queued for local execution preview."]); setCommand(""); };
  return <div><WorkspaceHeader eyebrow="Developer operations" title="Console" description="Inspect runtime output and stage safe local commands without losing mission context." /><GlassPanel className="overflow-hidden"><div className="flex items-center justify-between border-b border-white/[0.07] px-4 py-3"><span className="flex items-center gap-2 text-xs font-bold text-slate-300"><TerminalSquare size={15} className="text-cyan-300" /> orion@mission-control</span><span className="flex items-center gap-1.5 text-[10px] text-emerald-300"><CircleDot size={11} /> connected</span></div><div aria-live="polite" className="min-h-80 space-y-2 bg-black/35 p-5 font-mono text-xs leading-6 text-slate-300">{lines.map((line, index) => <p key={`${line}-${index}`} className={line.startsWith("›") ? "text-cyan-200" : ""}>{line}</p>)}</div><form onSubmit={execute} className="flex gap-2 border-t border-white/[0.07] p-3"><span className="self-center font-mono text-cyan-300">›</span><input aria-label="Console command" value={command} onChange={(event) => setCommand(event.target.value)} placeholder="status" className={`${fieldClass} border-0 bg-transparent font-mono focus:border-0`} /><button className={buttonClass}><CheckCircle2 size={14} /> Execute</button></form></GlassPanel></div>;
}
