"use client";
import { useCallback, useEffect, useState } from "react";
import { Bell, Command, Menu, PanelRight, Search } from "lucide-react";
import { ORION_BUILD } from "@/lib/orion-build";
import { apiGet } from "@/lib/api/client";
import { useUiStore } from "@/store/ui-store";
import { StatusBadge } from "./data-display/StatusBadge";
type Status={status:string;version:string};type Policy={active_policy?:{name?:string;key?:string}};
export function Topbar(){const ui=useUiStore();const [status,setStatus]=useState<Status|null>(null);const [policy,setPolicy]=useState<Policy|null>(null);const refresh=useCallback(async()=>{const [health,security]=await Promise.allSettled([apiGet<Status>("/api/status"),apiGet<Policy>("/api/security/policy")]);setStatus(health.status==="fulfilled"?health.value:null);setPolicy(security.status==="fulfilled"?security.value:null)},[]);useEffect(()=>{void refresh();const id=window.setInterval(()=>{if(document.visibilityState==="visible")void refresh()},30_000);return()=>window.clearInterval(id)},[refresh]);return <header className="flex h-[72px] shrink-0 items-center gap-3 border-b border-white/10 bg-[rgba(7,10,16,.92)] px-3 backdrop-blur-xl sm:px-5"><button aria-label="Open navigation" onClick={()=>ui.setMobileNavOpen(true)} className="aurora-icon-button lg:hidden"><Menu size={19}/></button><button onClick={()=>ui.setCommandOpen(true)} className="flex min-w-0 flex-1 items-center gap-3 rounded-xl border border-white/10 bg-white/[0.035] px-3 py-2.5 text-left text-sm text-slate-500 hover:border-cyan-300/25 sm:max-w-xl"><Search size={17}/><span className="truncate">Search {ORION_BUILD.product} or run a safe command</span><kbd className="ml-auto hidden rounded-md border border-white/10 px-2 py-1 text-[11px] sm:block"><Command size={11} className="inline"/> K</kbd></button><div className="ml-auto flex items-center gap-2"><div className="hidden xl:block"><StatusBadge status={policy?.active_policy?.name??policy?.active_policy?.key??"Policy unavailable"} tone={policy?"info":"neutral"}/></div><div className="hidden sm:block"><StatusBadge status={status?"Online":"Offline"} tone={status?"success":"danger"}/></div><button aria-label="Open notifications" onClick={()=>ui.setNotificationsOpen(true)} className="aurora-icon-button"><Bell size={18}/></button><button aria-label="Toggle context rail" aria-expanded={ui.contextOpen} onClick={()=>ui.setContextOpen(!ui.contextOpen)} className="aurora-icon-button"><PanelRight size={18}/></button></div></header>}
