"use client";
import { useEffect } from "react";
import { Pin, Search } from "lucide-react";
import { memoryCategories } from "@/lib/memory-data";
import { useMemoryStore } from "@/store/memory-store";
import { useUiStore } from "@/store/ui-store";
import { GlassPanel } from "../aurora/glass-panel";
import { StatusChip } from "../aurora/status-chip";
export function MemoryVault() {
  const { memories, selectedId, query, category, setQuery, setCategory, selectMemory, togglePin } = useMemoryStore();
  const setOrbState = useUiStore((state) => state.setOrbState);
  useEffect(() => { setOrbState("thinking"); return () => setOrbState("idle"); }, [setOrbState]);
  const filtered = memories.filter((memory) => (category === "All Memory" || memory.category === category) && memory.title.toLowerCase().includes(query.toLowerCase()));
  const selected = memories.find((memory) => memory.id === selectedId) || memories[0];
  return <div className="grid gap-4 xl:grid-cols-[280px_minmax(0,1fr)_360px]"><GlassPanel className="p-4"><h2 className="font-black text-white">Memory Search</h2><div className="mt-4 flex items-center gap-2 rounded-xl border border-white/10 bg-black/20 px-3 py-2"><Search size={16}/><input value={query} onChange={(e) => setQuery(e.target.value)} className="min-w-0 flex-1 bg-transparent text-sm outline-none" placeholder="Search memory..."/></div><div className="mt-4 space-y-2">{memoryCategories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`w-full rounded-xl px-3 py-2 text-left text-sm ${item === category ? "bg-[#4F8BFF]/15 text-white" : "text-slate-400 hover:bg-white/[0.04]"}`}>{item}</button>)}</div></GlassPanel><div className="space-y-4"><GlassPanel className="p-5"><h1 className="text-2xl font-black text-white">Memory Vault</h1><p className="mt-2 text-slate-400">Searchable, inspectable, visual memory for O.R.I.O.N.</p></GlassPanel><div className="grid gap-3 md:grid-cols-2">{filtered.map((memory) => <button key={memory.id} onClick={() => selectMemory(memory.id)} className="rounded-[16px] border border-white/10 bg-[#11151D]/75 p-4 text-left hover:border-[#61DFFF]/30"><div className="flex justify-between"><StatusChip tone={memory.tone}>{memory.category}</StatusChip><button aria-label="Pin memory" onClick={(e) => { e.stopPropagation(); togglePin(memory.id); }}><Pin size={16} className={memory.pinned ? "text-[#FFC857]" : "text-slate-500"}/></button></div><h3 className="mt-3 font-bold text-white">{memory.title}</h3><p className="mt-2 text-sm text-slate-400">{memory.content}</p><p className="mt-3 text-xs text-slate-500">{memory.confidence}% confidence · {memory.lastUpdated}</p></button>)}</div><MemoryGraph/></div><GlassPanel className="p-5"><h2 className="text-xl font-black text-white">Selected Memory</h2><p className="mt-3 font-bold text-[#61DFFF]">{selected.title}</p><p className="mt-3 text-sm leading-6 text-slate-300">{selected.content}</p><div className="mt-4 flex flex-wrap gap-2">{selected.tags.map((tag) => <StatusChip key={tag} tone="muted">#{tag}</StatusChip>)}</div><p className="mt-4 text-xs text-slate-500">Source: {selected.source}<br/>Project: {selected.project}</p></GlassPanel></div>;
}
function MemoryGraph() { const nodes = ["User", "Projects", "Preferences", "Skills", "Conversations", "Tools", "System"]; return <GlassPanel className="p-5"><h2 className="font-black text-white">Memory Graph</h2><svg viewBox="0 0 600 180" className="mt-4 h-44 w-full"><circle cx="300" cy="90" r="28" fill="#4F8BFF33" stroke="#61DFFF"/>{nodes.slice(1).map((node, index) => { const x = 80 + index * 88; const y = index % 2 ? 140 : 40; return <g key={node}><line x1="300" y1="90" x2={x} y2={y} stroke="#61DFFF55"/><circle cx={x} cy={y} r="18" fill="#11151D" stroke="#7B5CFF"/><text x={x} y={y + 34} textAnchor="middle" fill="#94a3b8" fontSize="12">{node}</text></g>; })}<text x="300" y="94" textAnchor="middle" fill="white" fontSize="12">User</text></svg></GlassPanel>; }
