export type AgentStatus = "Running" | "Idle" | "Waiting" | "Paused" | "Completed" | "Error";
export type OrionAgent = { id: string; name: string; role: string; description: string; status: AgentStatus; progress: number; currentTask: string; model: string; cpu: number; memory: number; tokens: string; runtime: string; priority: string; logs: string[]; missionQueue: string[] };
export const agents: OrionAgent[] = [
  { id: "planner", name: "Planner", role: "Strategist", description: "Breaks user intent into safe executable plans.", status: "Running", progress: 72, currentTask: "Sequencing workspace phase plan", model: "GPT-5.5", cpu: 28, memory: 42, tokens: "18.2k", runtime: "12m", priority: "High", logs: ["Loaded project context", "Generated task graph", "Waiting on safety layer"], missionQueue: ["Define steps", "Assign agents", "Request approval"] },
  { id: "researcher", name: "Researcher", role: "Discovery", description: "Collects context and summarizes findings.", status: "Waiting", progress: 44, currentTask: "Awaiting browser approval", model: "Claude", cpu: 12, memory: 31, tokens: "9.7k", runtime: "8m", priority: "Medium", logs: ["Prepared search query", "Sandbox check passed"], missionQueue: ["Open browser", "Summarize sources"] },
  { id: "coder", name: "Coder", role: "Builder", description: "Creates implementation patches.", status: "Running", progress: 61, currentTask: "Refactoring Aurora shell", model: "GPT-5.5", cpu: 46, memory: 58, tokens: "31.4k", runtime: "22m", priority: "High", logs: ["Created components", "Updated stores", "Running typecheck"], missionQueue: ["Patch files", "Run build"] },
  { id: "tester", name: "Tester", role: "Validation", description: "Runs checks and reports regressions.", status: "Idle", progress: 18, currentTask: "Standby", model: "Local LLM", cpu: 5, memory: 11, tokens: "2.1k", runtime: "2m", priority: "Low", logs: ["No active suite"], missionQueue: ["Typecheck", "Build"] },
  { id: "docs", name: "Documentation", role: "Scribe", description: "Captures decisions and handoff notes.", status: "Completed", progress: 100, currentTask: "Summary ready", model: "Gemini", cpu: 4, memory: 9, tokens: "5.3k", runtime: "5m", priority: "Medium", logs: ["Generated release notes"], missionQueue: ["Write changelog"] },
  { id: "memory", name: "Memory Manager", role: "Context", description: "Indexes and retrieves durable knowledge.", status: "Running", progress: 83, currentTask: "Linking project memories", model: "GPT-5.5", cpu: 18, memory: 63, tokens: "14k", runtime: "16m", priority: "High", logs: ["Indexed 12 snippets", "Merged duplicate memory"], missionQueue: ["Pin memory", "Refresh graph"] },
  { id: "security", name: "Security Guardian", role: "Safety", description: "Reviews risky actions and approvals.", status: "Waiting", progress: 50, currentTask: "Reviewing terminal command", model: "Claude", cpu: 9, memory: 22, tokens: "6.9k", runtime: "9m", priority: "Critical", logs: ["Command requires approval"], missionQueue: ["Risk classify", "Request decision"] },
  { id: "deploy", name: "Deployment", role: "Release", description: "Packages and verifies deployments.", status: "Paused", progress: 35, currentTask: "Paused by user", model: "Local LLM", cpu: 0, memory: 8, tokens: "1.2k", runtime: "3m", priority: "Medium", logs: ["Deployment paused"], missionQueue: ["Build", "Tag", "Deploy"] },
];
