import type { DemoWalkthroughStep } from "@/types/demo";

export const ORION_DEMO_WALKTHROUGH_STEPS: DemoWalkthroughStep[] = [
  { id: "intro-dashboard", stepNumber: 1, title: "Open Aurora OS", subtitle: "Introduce O.R.I.O.N. as a local-first AI desktop agent.", description: "Begin with the full dashboard and explain that Aurora OS is the visual command center for O.R.I.O.N.", panelId: "dashboard-intelligence", viewId: "full-mission-control", callout: "Aurora OS is designed to feel like an AI-native operating system, not a basic chatbot.", talkingPoints: ["O.R.I.O.N. stands for Operational Response and Intelligent Orchestration Network.", "Aurora OS is the dashboard interface.", "The project focuses on safe agentic workflows."] },
  { id: "dashboard-intelligence", stepNumber: 2, title: "Dashboard Intelligence", subtitle: "Show system score, readiness, and recommendations.", description: "Use the intelligence panel to explain live system awareness and release readiness.", panelId: "dashboard-intelligence", viewId: "full-mission-control", callout: "Dashboard Intelligence gives a quick health snapshot of the whole system.", talkingPoints: ["Show intelligence score.", "Explain readiness label.", "Point out recommendations and release metrics."] },
  { id: "security-architecture", stepNumber: 3, title: "Security Architecture", subtitle: "Switch to Security View.", description: "Explain how O.R.I.O.N. controls tools through plugins, policies, permissions, and audit logs.", panelId: "security-policy", viewId: "security-view", callout: "Security View proves that O.R.I.O.N. is designed around visibility and controlled execution.", talkingPoints: ["Show Security Policy modes.", "Show Plugin System.", "Show Tool Permission Enforcement.", "Show Tool Audit Center."] },
  { id: "developer-view", stepNumber: 4, title: "Developer View", subtitle: "Show stabilization and frontend architecture tools.", description: "Switch to Developer View and explain codebase health, frontend refactor scanning, and desktop support.", panelId: "stabilization", viewId: "developer-view", callout: "Developer View shows how the system checks itself during development.", talkingPoints: ["Show Stabilization Manager.", "Show Frontend Refactor Manager.", "Show Desktop Shell.", "Show Backend Sidecar."] },
  { id: "release-view", stepNumber: 5, title: "Release View", subtitle: "Show release readiness and verification.", description: "Switch to Release View and explain Quality Gate, Release Candidate, Public Release, and GitHub Polish.", panelId: "release-candidate", viewId: "release-view", callout: "Release View demonstrates how O.R.I.O.N. prepares itself for portfolio delivery.", talkingPoints: ["Run or show Quality Gate.", "Show Release Candidate checklist.", "Show Public Release package.", "Show GitHub Polish readiness."] },
  { id: "portfolio-showcase", stepNumber: 6, title: "Portfolio Showcase", subtitle: "Show screenshots, case study, and demo narrative.", description: "Use the portfolio panels to summarize the public project story.", panelId: "portfolio-case-study", viewId: "release-view", callout: "The Portfolio Case Study turns the technical build into a clear public story.", talkingPoints: ["Show Screenshot Gallery.", "Show Portfolio Case Study.", "Show Portfolio Demo sequence.", "Explain the problem, solution, architecture, and outcome."] },
  { id: "closing", stepNumber: 7, title: "Closing Summary", subtitle: "Finish with O.R.I.O.N.'s value.", description: "Close by explaining the project as a safe, local-first AI operating dashboard.", panelId: "portfolio-demo", viewId: "release-view", callout: "O.R.I.O.N. demonstrates safe agent orchestration, system intelligence, and portfolio-ready AI product design.", talkingPoints: ["Safe tool orchestration.", "Approval-gated execution.", "Release verification.", "Public portfolio packaging."] },
];

export function getDemoStep(index: number) { return ORION_DEMO_WALKTHROUGH_STEPS[index] || ORION_DEMO_WALKTHROUGH_STEPS[0]; }
