// Generated by scripts/sync_release_manifest.py; do not edit.
export const ORION_BUILD = {
  product: "O.R.I.O.N.",
  productName: "Operational Response and Intelligent Orchestration Network",
  interface: "Aurora OS",
  version: "6.7.0",
  versionLabel: "v6.7.0",
  channel: "development",
  releaseName: "Aurora Mission Control",
} as const;
