import type { AuroraDashboardViewId, AuroraDashboardViewPreset, AuroraPanelDefinition, AuroraPanelId, AuroraPanelLayoutItem } from "@/types/panels";
const p = (id: AuroraPanelId,title:string,category:AuroraPanelDefinition["category"],group:AuroraPanelDefinition["group"],order:number,pinned=false):AuroraPanelDefinition=>({id,title,description:`${title} Aurora OS module.`,category,group,defaultVisible:true,defaultPinned:pinned,defaultOrder:order,version:"v4.7"});
export const AURORA_PANEL_REGISTRY=[p("dashboard-intelligence","Dashboard Intelligence","core","mission-control",10,true),p("dashboard-layout","Dashboard Layout","settings","settings",15,true),p("dashboard-view-selector","Dashboard Views","settings","settings",16,true),p("release-candidate","Release Candidate","release","release",20,true),p("stabilization","Stabilization Manager","diagnostics","developer",30),p("frontend-refactor","Frontend Refactor","diagnostics","developer",40),p("plugin-system","Plugin System","security","security",50,true),p("security-policy","Security Policy","security","security",60,true),p("tool-permission","Tool Permission Enforcement","security","security",70),p("tool-audit","Tool Audit Center","security","security",80),p("desktop-shell","Desktop App Shell","desktop","desktop",90),p("backend-sidecar","Backend Sidecar","desktop","desktop",100),p("notification-engine","Notification Engine","workflow","productivity",110),p("user-settings","User Profile + Settings","settings","settings",120)] as AuroraPanelDefinition[];
export const AURORA_DASHBOARD_PRESETS:AuroraDashboardViewPreset[]=[
{id:"full-mission-control",name:"Full Mission Control",description:"Every Aurora OS module.",icon:"👽",panelIds:AURORA_PANEL_REGISTRY.map(x=>x.id),pinnedPanelIds:["dashboard-intelligence","dashboard-view-selector","dashboard-layout","release-candidate","plugin-system","security-policy"]},
{id:"security-view",name:"Security View",description:"Plugins, policy, permissions, and audit.",icon:"🛡️",panelIds:["dashboard-intelligence","dashboard-view-selector","plugin-system","security-policy","tool-permission","tool-audit","user-settings"],pinnedPanelIds:["dashboard-intelligence","dashboard-view-selector","security-policy","plugin-system"]},
{id:"developer-view",name:"Developer View",description:"Diagnostics and desktop operations.",icon:"🧠",panelIds:["dashboard-intelligence","dashboard-view-selector","stabilization","frontend-refactor","desktop-shell","backend-sidecar","plugin-system"],pinnedPanelIds:["dashboard-intelligence","dashboard-view-selector","stabilization","frontend-refactor"]},
{id:"release-view",name:"Release View",description:"Release readiness and diagnostics.",icon:"🚀",panelIds:["dashboard-intelligence","dashboard-view-selector","release-candidate","stabilization","frontend-refactor","tool-audit","security-policy"],pinnedPanelIds:["dashboard-intelligence","dashboard-view-selector","release-candidate"]},
{id:"minimal-view",name:"Minimal View",description:"Daily intelligence, reminders, and settings.",icon:"✨",panelIds:["dashboard-intelligence","dashboard-view-selector","notification-engine","user-settings"],pinnedPanelIds:["dashboard-intelligence","dashboard-view-selector"]}];
export const createDefaultPanelLayout=():AuroraPanelLayoutItem[]=>AURORA_PANEL_REGISTRY.map(({id,defaultVisible:visible,defaultPinned:pinned,defaultOrder:order})=>({id,visible,pinned,order}));
export const getPanelDefinition=(id:AuroraPanelId)=>AURORA_PANEL_REGISTRY.find(x=>x.id===id); export const getDashboardPreset=(id:AuroraDashboardViewId)=>AURORA_DASHBOARD_PRESETS.find(x=>x.id===id);
export const createLayoutFromPreset=(id:AuroraDashboardViewId):AuroraPanelLayoutItem[]=>{const preset=getDashboardPreset(id);if(!preset)return createDefaultPanelLayout();return AURORA_PANEL_REGISTRY.map(x=>({id:x.id,visible:preset.panelIds.includes(x.id),pinned:preset.pinnedPanelIds.includes(x.id),order:x.defaultOrder}));};
export const sortPanelLayout=(layout:AuroraPanelLayoutItem[])=>[...layout].sort((a,b)=>a.pinned===b.pinned?a.order-b.order:a.pinned?-1:1);
