import type { RecordingScene } from "@/types/recording";
export const ORION_RECORDING_SCENES: RecordingScene[] = [
  { id: "opening", title: "Opening Scene", subtitle: "Introduce O.R.I.O.N. and Aurora OS.", viewId: "full-mission-control", callout: "O.R.I.O.N. is a local-first AI desktop agent with a futuristic dashboard called Aurora OS.", checklist: ["Aurora OS visible", "Dashboard Intelligence loaded", "Backend online", "No private data visible"] },
  { id: "dashboard", title: "Dashboard Intelligence", subtitle: "Show system awareness and readiness.", viewId: "full-mission-control", callout: "Dashboard Intelligence gives a high-level view of system health, readiness, and recommendations.", checklist: ["Show intelligence score", "Show readiness label", "Show recommendations", "Explain system visibility"] },
  { id: "security", title: "Security Architecture", subtitle: "Show policy, plugins, permissions, and audit.", viewId: "security-view", callout: "O.R.I.O.N. is designed around controlled execution, plugin permissions, and audit visibility.", checklist: ["Show Security Policy", "Show Plugin System", "Show Tool Permission Enforcement", "Show Tool Audit Center"] },
  { id: "developer", title: "Developer View", subtitle: "Show stabilization and frontend architecture.", viewId: "developer-view", callout: "Developer View shows how O.R.I.O.N. checks its own codebase and desktop runtime.", checklist: ["Show Stabilization Manager", "Show Frontend Refactor", "Show Desktop Shell", "Show Backend Sidecar"] },
  { id: "release", title: "Release View", subtitle: "Show Quality Gate, Release Candidate, and Public Release.", viewId: "release-view", callout: "Release View proves the project can verify, package, and present itself safely.", checklist: ["Show Quality Gate", "Show Release Candidate", "Show Public Release", "Show GitHub Polish"] },
  { id: "portfolio", title: "Portfolio Showcase", subtitle: "Show screenshots and case study story.", viewId: "release-view", callout: "The Portfolio Showcase turns the technical system into a clear public project narrative.", checklist: ["Show Screenshot Gallery", "Show Portfolio Case Study", "Show Portfolio Demo", "Show Guided Walkthrough"] },
  { id: "closing", title: "Closing Scene", subtitle: "Summarize the value of O.R.I.O.N.", viewId: "minimal-view", callout: "O.R.I.O.N. demonstrates safe agent orchestration, local-first AI workflows, and operating-system style product design.", checklist: ["Summarize safety model", "Summarize architecture", "Mention public release package", "End cleanly"] },
];
export const getRecordingScene = (sceneId: string) => ORION_RECORDING_SCENES.find((scene) => scene.id === sceneId) || ORION_RECORDING_SCENES[0];
