import { ApprovalAction, ToolEvent } from "./tool-types";
export const toolEvents: ToolEvent[] = [
  { id: "e1", type: "browser", title: "Browser opened", description: "Opened docs in isolated browser.", status: "Completed", risk: "Low", tool: "browser.open", agent: "Researcher", project: "Aurora OS", time: "08:41", duration: "2s", input: "docs", output: "Page loaded", reason: "Gather design references", requiresApproval: false, tone: "success" },
  { id: "e2", type: "search", title: "Web search started", description: "Searching architecture patterns.", status: "Running", risk: "Low", tool: "search.query", agent: "Researcher", project: "Aurora OS", time: "08:42", duration: "live", input: "AI OS dashboard", output: "Collecting", reason: "Inform UI plan", requiresApproval: false, tone: "primary" },
  { id: "e3", type: "file", title: "Generated component file", description: "Created app shell component.", status: "Completed", risk: "Medium", tool: "file.write", agent: "Coder", project: "Aurora OS", time: "08:43", duration: "6s", input: "app-shell.tsx", output: "File written", reason: "Implement shell", requiresApproval: false, tone: "success" },
  { id: "e4", type: "terminal", title: "Terminal command requested", description: "Build validation requested.", status: "Waiting Approval", risk: "High", tool: "terminal.exec", agent: "Tester", project: "Aurora OS", time: "08:44", duration: "pending", input: "npm run build", output: "Awaiting approval", reason: "Validate compile", requiresApproval: true, tone: "warning" },
  { id: "e5", type: "python", title: "Python execution completed", description: "Generated mock data summary.", status: "Completed", risk: "Low", tool: "python.run", agent: "Planner", project: "O.R.I.O.N.", time: "08:45", duration: "1s", input: "summarize", output: "Summary ready", reason: "Plan data", requiresApproval: false, tone: "success" },
  { id: "e6", type: "memory", title: "Memory updated", description: "Stored dashboard preference.", status: "Completed", risk: "Low", tool: "memory.write", agent: "Memory Manager", project: "Aurora OS", time: "08:46", duration: "1s", input: "preference", output: "Indexed", reason: "Persist UX context", requiresApproval: false, tone: "success" },
  { id: "e7", type: "git", title: "Git commit queued", description: "Commit requires review.", status: "Queued", risk: "Medium", tool: "git.commit", agent: "Coder", project: "Aurora OS", time: "08:47", duration: "queued", input: "commit", output: "Queued", reason: "Save work", requiresApproval: true, tone: "warning" },
  { id: "e8", type: "workflow", title: "Workflow failed", description: "Release workflow blocked by missing secret.", status: "Failed", risk: "Critical", tool: "workflow.run", agent: "Deployment", project: "Aurora OS", time: "08:48", duration: "11s", input: "deploy", output: "Missing secret", reason: "Release preview", requiresApproval: false, tone: "danger" },
];
export const approvals: ApprovalAction[] = [
  { id: "a1", title: "Run production build", description: "Validate the frontend bundle.", tool: "terminal.exec", requestedBy: "Tester", project: "Aurora OS", risk: "High", status: "Pending", command: "npm run build", time: "08:44" },
  { id: "a2", title: "Create git commit", description: "Commit current frontend changes.", tool: "git.commit", requestedBy: "Coder", project: "Aurora OS", risk: "Medium", status: "Pending", command: "git commit", time: "08:47" },
];
