export const guideWorkflows = [
  {
    id: "workspace-workflow", title: "1. Register a workspace, then choose work",
    purpose: "A workspace is a trusted local folder—not an approval or an automatically running agent.",
    steps: [
      "Prepare a non-sensitive sample folder. In Workspaces, enter its name and full existing path, read both consent statements, then Register trusted workspace.",
      "Confirm the saved canonical path and workspace ID. Registration creates no approval, does not index documents and does not launch a program.",
      "For a conversation, open Assistant → Context sent to the provider → Workspace. Choose the folder and source inclusion, then Preview Context before Send. The sidebar workspace selection saves a preference; check each workflow's own selector.",
      "For document questions, open Knowledge, select the workspace and a relative source path, explicitly consent to indexing, then index only needed files. Search and inspect provenance. This requires an allowed knowledge capability.",
      "For planned work, open Missions and put the workspace ID, target files and limits in the goal. For a desktop action, choose Request folder, Request VS Code or Request dev server. Only a response with an approval ID means a request reached the queue.",
    ],
    caution: "Strict Mode disables desktop, knowledge and advanced developer plugins. A denied action creates no approval. Review the needed capability before considering a profile change.",
    links: [{ href: "/workspaces", label: "Open Workspaces" }, { href: "/assistant", label: "Choose Assistant context" }, { href: "/knowledge", label: "Open Knowledge" }],
  },
  {
    id: "approval-workflow", title: "2. Understand an empty approval queue",
    purpose: "An approval is permission for one concrete action—not a workspace-registration receipt.",
    steps: [
      "No request yet: registration and saving a mission leave the queue empty. Request an intended action only when you actually need it.",
      "Denied before approval: the originating screen says a plugin/tool is disabled or policy denies it. Read the reason and Audit evidence. No approval ID is created; refreshing cannot override policy.",
      "Request accepted: note the approval ID, open Approvals → Refresh queue and find that ID. Inspect the owner, mission/step if present, exact target, normalized arguments, risk and expected effect.",
      "Reject unexpected actions with a reason. Approve once only if you understand the whole action. For npm build/dev, inspect resolved scripts and lifecycle hooks: these can execute arbitrary workspace code.",
      "Read the result. Executing means claimed, not completed. Approved, rejected and failed rows leave the pending queue; use Show recent history. Return to the owning mission and continue explicitly if ready.",
    ],
    caution: "A direct Folder/VS Code request has no mission owner; approving it does not start a mission. Terminal approvals cannot grant fresh permission, and approval cannot make a disabled capability executable.",
    links: [{ href: "/approvals", label: "Open Approvals" }, { href: "/audit", label: "Inspect decisions" }, { href: "/security", label: "Review policy" }],
  },
  {
    id: "mission-workflow", title: "3. Run a mission one step at a time",
    purpose: "A mission is a saved goal and ordered steps. Ready does not mean running or scheduled.",
    steps: [
      "Check Backend connected in the top bar. An administrator must configure a valid provider key/model before AI execution. Local planning does not prove the provider works.",
      "In Missions → Create a mission from your goal, enter a title and a precise goal. Include the registered workspace ID, intended files, read-only or write limits and completion condition. Example: Review workspace ID [your ID], read only its sample README, report three findings with evidence, and do not change files.",
      "Add small steps: inspect the specified source; identify risks; summarize evidence. Review the order and Save mission plan. Refresh to confirm persistence. The sidebar workspace preference is not a mission-scoped security boundary.",
      "Choose Run Next Step once on the saved mission. It starts one bounded AI cycle, not a guarantee of success. Read output and durable state. Use Run 3 Steps only after understanding the one-step flow.",
      "Waiting for approval: find the matching mission and step in Approvals and decide. A successful action resolves only its owning continuation. Return to Missions and run the next eligible cycle to evaluate/continue; approving does not launch a new unattended batch.",
      "Paused: Resume restores eligibility, then choose Run Next Step. Failed/Blocked: inspect run and audit evidence, resolve the cause and use Retry failed step only where offered. If no safe recovery control is offered, stop and ask the administrator.",
      "Complete: inspect step results and use Report. Cancel prevents future execution but cannot undo previous actions. A Daily timetable mission can draft a timetable; its title does not create recurring execution.",
    ],
    caution: "Goal text is not a filesystem sandbox: tool policy and registered-root checks still apply. Assistant context toggles control that conversation, not automatically mission runs. Do not use sensitive material for introductory missions.",
    links: [{ href: "/missions", label: "Create or review a mission" }, { href: "/approvals", label: "Review its approval" }, { href: "/activity", label: "Read history" }],
  },
  {
    id: "security-profiles", title: "4. Change capabilities deliberately",
    purpose: "Profiles change plugin availability. They do not deploy the app, isolate environments or bypass approvals.",
    steps: [
      "Strict Mode: use it for training and core planning, memory and workspace registration. It disables desktop, knowledge/vector, browser research, voice, blueprints and advanced developer plugins.",
      "Balanced: enables the broader installed capability set, including desktop, knowledge and developer tools. Review why these are needed. Per-tool disablement, trusted roots and specific approvals still apply.",
      "Developer Lab: currently enables the same broad plugin set as Balanced and uses the experimental safety-level label. It is not an OS sandbox and does not provide stronger isolation or approval-free execution.",
      "Before changing profile, pause active missions and inspect pending/executing approvals. A change cannot undo in-flight effects. Have the responsible operator authorize the access and preserve backups before enabling code or file-write capabilities.",
      "Open Security → Security Policy, inspect the target profile's counts and description, then Apply deliberately. Wait for the backend response; verify Active Policy and Recent Policy Events. A click or saved preference is not proof of success.",
      "Inspect Tools and Plugins for effective availability, request a fresh intended action and verify its response. After the task, review evidence and restore the restrictive profile required by your operator.",
    ],
    caution: "Only the responsible operator should broaden access. Never disable authentication or approval enforcement to solve a connection or permission error. No profile certifies production readiness.",
    links: [{ href: "/security", label: "Inspect Security Policy" }, { href: "/tools", label: "Inspect permissions" }, { href: "/plugins", label: "Inspect plugins" }],
  },
  {
    id: "production-workflow", title: "5. Understand production and environment labels",
    purpose: "Production / Development / Demo in the sidebar is a saved label—not separate databases, credentials, networks or trusted roots.",
    steps: [
      "Train in a disposable sample folder. Do not use customer data or live services merely because the sidebar says Production.",
      "For operational use, require an administrator-reviewed deployment, provider/data-sharing policy, least-privilege access, tested backups/restore and valid release evidence. The development launcher is not a production deployment.",
      "Provision real environment separation through separate application state, workspace roots and credentials under administrator control. A label or profile change provides none of that isolation.",
      "Review Release Center's exact CI/artifact evidence and Diagnostics for the installed system. Stop if required checks, storage integrity or recovery procedures are unverified.",
      "Run the smallest planned unit, inspect scope, approve only necessary actions, retain Activity/Audit evidence and validate the result. Know how to stop and recover before expanding the workflow.",
    ],
    caution: "O.R.I.O.N. 6.7.0 remains a development application. No security profile converts it into a certified production system. Do not use business-critical data based on its environment label.",
    links: [{ href: "/release", label: "Inspect release evidence" }, { href: "/system", label: "Check diagnostics" }, { href: "/analytics", label: "View live operations" }],
  },
];

type SidebarLesson = { steps: string[]; result: string };
export const sidebarLessons: Record<string, SidebarLesson> = {
  "/": { steps: ["Check backend connection and meaningful activity.", "Choose Assistant for a question, Missions for a reviewed sequence or Approvals for an actual request."], result: "A next action—not proof that work already succeeded." },
  "/assistant": { steps: ["Start New conversation; choose Workspace and source inclusion under Context sent to the provider.", "Preview Context, Send a bounded request, then inspect results and approval interruptions."], result: "An inspectable response, not automatically a saved mission. Semantic search can send queries to an embedding provider." },
  "/missions": { steps: ["Write goal, scope and ordered steps; Save mission plan.", "Run Next Step, inspect state, resolve its approval if needed and continue explicitly. Use Report afterward."], result: "Durable plans and results; Ready does not mean running or scheduled." },
  "/approvals": { steps: ["Match an approval ID to its exact target and owner.", "Approve once or Reject with a reason; read results and Show recent history afterward."], result: "A recorded decision/outcome. Registration and denied requests produce no pending approval." },
  "/activity": { steps: ["Read mission, approval and failure messages.", "Inspect the affected record and Audit before retrying."], result: "Human-readable history, not a replacement for exact execution evidence." },
  "/memory": { steps: ["Inspect content, scope, provenance and sensitivity.", "Edit, exclude or delete unwanted facts before future retrieval."], result: "Controlled future context; removal does not recall text already sent to a provider or earlier conversation." },
  "/knowledge": { steps: ["Select a trusted workspace and relative source path; explicitly consent to indexing.", "Index needed files, check results, search and inspect provenance before use in Assistant."], result: "Searchable sources. Registration is not indexing, and Strict Mode may deny this capability." },
  "/workspaces": { steps: ["Register an existing folder with trust/source consent and confirm its ID/canonical path.", "Choose Assistant, a scoped mission, Knowledge or an intended desktop request."], result: "An authorized source, not an automatic scan, mission or approval." },
  "/developer": { steps: ["Select a sample workspace, inspect, describe the issue, diagnose and review a patch plan.", "Review the relative path/replacement content, request patch approval, then inspect backup evidence and validate changes."], result: "Controlled development. A plan is not an applied patch; commands/scripts remain high risk." },
  "/tools": { steps: ["Inspect capability, owning plugin, risk and effective permission reason.", "Request the capability from its workflow; resolve denials with the operator."], result: "Understand availability. Listed does not mean enabled or approved." },
  "/plugins": { steps: ["Inspect installed plugins, tools, enabled state and permissions.", "Have the operator review changes; check Tools for effective access and Audit for decisions."], result: "Capability governance, not a marketplace for arbitrary untrusted code." },
  "/security": { steps: ["Review Active Policy, profile effects and events.", "Pause affected work, obtain operator authorization, Apply deliberately and verify the backend result."], result: "Changed availability, not production certification or approval replay permission." },
  "/audit": { steps: ["Inspect actor, tool, policy, mission/step, approval and correlation evidence.", "Distinguish allowed decisions from execution starts and terminal results."], result: "Evidence for investigation; allowed does not mean completed." },
  "/release": { steps: ["Review build identity, required checks and exact artifact evidence.", "Ask the release owner to resolve failures before any freeze or release decision."], result: "Engineering evidence; historical milestones and health scores do not certify an installer." },
  "/analytics": { steps: ["Use Live operations for connection, current execution and approvals; refresh or wait 30 seconds.", "Use the separate historical time ranges and inspect metric definitions."], result: "Current state plus event history. Unavailable is not zero; Ready is not Running." },
  "/system": { steps: ["Inspect backend, desktop, storage and recovery findings.", "Read errors and review effects before using recovery/export controls."], result: "A diagnosis and safe next step; do not delete databases or kill unknown processes." },
  "/settings": { steps: ["Set profile, appearance, density, notifications and pet preferences.", "Review explanations before saving; keep keys private and change permissions in Security."], result: "Saved preferences. Environment/model labels do not provision infrastructure or provider access." },
  "/help": { steps: ["Practice the workflows above with a trainer and sample data.", "Demonstrate a safe rejection, context review and finding audit evidence."], result: "A repeatable routine. If you cannot explain an action, do not approve it." },
};
